# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=1)),
                ('phone', models.CharField(max_length=20)),
                ('birth', models.CharField(max_length=8)),
                ('part', models.CharField(max_length=1)),
                ('create_dt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
