# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-16 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_remove_person_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth',
            field=models.DateField(),
        ),
    ]
