# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-16 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_person_birth_monthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='part',
            field=models.CharField(choices=[('S', '소프라노'), ('A', '알토'), ('T', '테너'), ('B', '베이스')], max_length=1),
        ),
    ]
