# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-16 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_auto_20160416_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_monthday',
            field=models.CharField(default='', max_length=4),
        ),
    ]
